import { createHash } from 'node:crypto';
import { modesOf, servicesOf, type GeoEdge, type GeoNode } from '@odyssey/engine';

/**
 * Serialise the graph to the committed artifacts, deterministically.
 *
 * ## Valid JSON *and* one record per line
 *
 * The obvious diff-friendly format is JSONL with `//` headers — and it produces a `.json` file
 * that `JSON.parse` rejects, which is a trap for every tool and every human who opens it. So
 * the file is a real JSON object whose record arrays are laid out one element per line. Both
 * properties at once: a regeneration is a reviewable diff rather than a 17,000-line reflow, and
 * the loader is still `JSON.parse`.
 *
 * That layout is also why both files are in `.prettierignore`: Prettier would expand every
 * record across ten lines and make `geo:build --check` permanently red.
 *
 * ## A custom serialiser, never raw `JSON.stringify` over an object literal
 *
 * Key order in a literal is insertion order — a property of the code that built it rather than
 * of the data — so a refactor that reorders two assignments would rewrite every line. Writing
 * the fields explicitly makes the on-disk shape a stated decision. ADR 0024 Decision 6.
 *
 * Short keys because ~1,200 nodes and ~3,000 edges pay for every character. The mapping is
 * stated in each file's own `_format` block rather than left to be inferred.
 */

export type NodeRecordExtras = {
  /** The one user-visible literal content data may carry. Null on crossings and waypoints. */
  readonly name: string | null;
  /** Quantised to 1e-5 degrees. For rendering — the ENGINE never sees a coordinate. */
  readonly lat: number;
  readonly lng: number;
};

function nodeLine(node: GeoNode, extras: NodeRecordExtras): string {
  return JSON.stringify({
    id: String(node.id),
    n: extras.name,
    y: extras.lat,
    x: extras.lng,
    t: node.type,
    tr: node.terrain,
    e: node.elevationM,
    p: node.population,
    s: [...servicesOf(node.services)],
    cm: [...node.closedMonths],
  });
}

function edgeLine(edge: GeoEdge): string {
  return JSON.stringify({
    id: String(edge.id),
    a: String(edge.from),
    b: String(edge.to),
    d: edge.distanceKm,
    m: [...modesOf(edge.modes)],
    td: edge.terrainDifficulty,
    sc: edge.scenic,
    sz: edge.seasonality,
    tl: edge.tolled,
    ab: edge.adminBoundary,
  });
}

/**
 * Stable digest of the node SET, so an edge file cannot silently drift from the nodes it was
 * built against. `GEO_NODES_DIGEST_STALE` recomputes it at lint time.
 */
export function nodesDigest(nodes: readonly GeoNode[]): string {
  const hash = createHash('sha256');
  for (const node of [...nodes].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))) {
    hash.update(String(node.id));
    hash.update('\n');
  }
  return hash.digest('hex').slice(0, 16);
}

const NODE_FORMAT = [
  'GENERATED by `pnpm geo:build`. Do not hand-edit — edit packages/content/geo/overlay.yaml.',
  'One record per line, sorted by id.',
  'id · n=name · y=lat · x=lng · t=type · tr=terrain · e=elevation m · p=population band',
  's=services · cm=closed months',
  'Place data (c) GeoNames contributors, CC BY 4.0, filtered and reformatted. Terrain and',
  'coastline from Natural Earth, public domain. See docs/geo-data-licensing.md.',
  'No countryCode, by design: there is no game consumer and point-in-polygon would ship a',
  'political assignment as fact. CLAUDE.md 11, ADR 0024 Decision 4.',
];

const EDGE_FORMAT = [
  'GENERATED by `pnpm geo:build`. Do not hand-edit — edit packages/content/geo/overlay.yaml.',
  'One record per line, sorted by id.',
  'id · a/b=endpoints · d=distance km · m=modes · td=terrain difficulty · sc=scenic',
  'sz=seasonality · tl=tolled · ab=crosses an administrative boundary',
  '`ab` is GEOMETRIC. It records WHERE a boundary is, never what happens there — difficulty',
  'comes from the route profile and the player state. CLAUDE.md 11.',
  'EVERY EDGE IS DERIVED from node coordinates and public-domain polygons. No road database',
  'was consulted, which is what keeps this file out of ODbL. docs/geo-data-licensing.md 2.',
];

export type Artifacts = {
  readonly nodesJson: string;
  readonly edgesJson: string;
  readonly digest: string;
};

/** `{ "_format": [...], "count": n, "nodes": [ <one per line> ] }`, hand-laid-out. */
function envelope(
  format: readonly string[],
  key: string,
  lines: readonly string[],
  extra: readonly string[] = [],
): string {
  const head = [
    '{',
    `  "_format": ${JSON.stringify(format)},`,
    ...extra,
    `  "count": ${String(lines.length)},`,
    `  "${key}": [`,
  ];
  const body = lines.map((line, i) => `    ${line}${i === lines.length - 1 ? '' : ','}`);
  return [...head, ...body, '  ]', '}', ''].join('\n');
}

export function writeArtifacts(
  nodes: readonly GeoNode[],
  extrasOf: (node: GeoNode) => NodeRecordExtras,
  edges: readonly GeoEdge[],
): Artifacts {
  const sortedNodes = [...nodes].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  const sortedEdges = [...edges].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  const digest = nodesDigest(sortedNodes);

  return {
    digest,
    nodesJson: envelope(
      NODE_FORMAT,
      'nodes',
      sortedNodes.map((node) => nodeLine(node, extrasOf(node))),
      [`  "digest": ${JSON.stringify(digest)},`],
    ),
    edgesJson: envelope(EDGE_FORMAT, 'edges', sortedEdges.map(edgeLine), [
      `  "nodesDigest": ${JSON.stringify(digest)},`,
    ]),
  };
}
